name: Build & Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write   # 👈 Isso permite fazer push para outras branches (como gh-pages)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build (ignore CI warnings)
        run: CI='' npm run build

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run deploy
